#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get staged JS and SCSS files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|scss)$')

if [ -n "$STAGED_FILES" ]; then
    # Only lint staged files
    echo "Linting staged files..."
    
    # Get staged JS files
    STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.js$')
    # Get staged SCSS files
    STAGED_SCSS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.scss$')
    
    # Lint JS files
    if [ -n "$STAGED_JS_FILES" ]; then
        echo "Linting JS files..."
        npx eslint $STAGED_JS_FILES --fix
    fi
    
    # Lint SCSS files
    if [ -n "$STAGED_SCSS_FILES" ]; then
        echo "Linting SCSS files..."
        npx stylelint $STAGED_SCSS_FILES --fix
    fi
    
    # Add back the modified files to staging
    echo "Adding fixed files back to staging..."
    git add $STAGED_FILES
fi